# Generated by Django 4.0.3 on 2022-04-19 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='details',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_id',
            field=models.UUIDField(default=uuid.UUID('18e0ccc3-4550-4a18-a2d2-260d68ecd036'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Idea ID'),
        ),
    ]
